### ISSUE TITLE
Namespace is not picking up from composer.json

### ISSUE THREAD

**Issue by MehediDracula** [fetzi/php-file-types#1]
I've tried on a fresh laravel installation but namespace is not picking up from `composer.json` all the time it's prompting for a namespace.

**Comment by fetzi** [comment]
Thx for the report, for me it is working atm but I'm currently doing a complete rewrite of the namespace lookup on file creation. I hope to tag the v1.1 version in the next days.

**Comment by fetzi** [comment]
what does your php project look like? is your namespace pointing to the src directory? maybe you can provide me with a screenshot?

the prompt for the namespace should only be a fallback tbh.

**Comment by MehediDracula** [comment]
I've tried on a fresh laravel installation

**Comment by fetzi** [comment]
@MehediDracula please update to v1.1.0 and check again!

**Comment by MehediDracula** [comment]
@fetzi still not working :worried:

**Comment by fetzi** [comment]
Which version of the extension do you have installed? Have you made a clean Laravel 5.5 installation?

**Comment by fetzi** [comment]
Fixed with 1.2.0
