### ISSUE TITLE
Add support for monorepos

### ISSUE THREAD

**Issue by fetzi** [fetzi/php-file-types#3]
A project in VS Code may contain multiple composer.json files that should be considered for namespace resolving.

For example:
```
- project1
    composer.json
    ...
- project2
    composer.json
    ...
```

When creating a new Class/Interface/Trait the closest composer.json file should be selected and used for namespace generation.

To save lookup time each found namespace is stored with its absolute base path in a "cache". This implementation limits the allowed composer.json folder level, but should be enough for monorepos.

**Comment by fetzi** [comment]
@shouze is this description correct for your use case?

**Comment by shouze** [comment]
@fetzi yes, perfect description :+1:
