### ISSUE TITLE
Namespace Issue on Laravel Generated Composer

### ISSUE THREAD

**Issue by kalesh13** [fetzi/php-file-types#5]
This is how my autoload field in composer looks like

`"autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },`

See Laravel generates composer files with a forward slash (app/). Even though Windows support both slashes, the default is a backward slash. Hence, when we create a new PHP class in Windows, the path uses backward slashes causing discrepancy with the composer forward slash.

The following condition will always fail in this scenario

` if (folder.startsWith(candidate['folder'])) {
                   ...
                }`

I suggest we use forward slash instead of path.sep. Can you fix this and release an update?

Thanks

**Comment by fetzi** [comment]
Yes, i will fix this. Would it be possible for you to test the new Version? If yes please send me yours email address to vscode@johannespichler.com
